// /*
//  * This source file was generated by the Gradle 'init' task
//  */
// package org.example;

// import org.junit.jupiter.api.Assertions;
// import org.junit.jupiter.api.Test;

// import io.quarkus.test.junit.QuarkusTest;

// @QuarkusTest
// public class AppTest {

//     @Test public void appHasAGreeting() {
//         App classUnderTest = new App();
//         Assertions.assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//     }
// }
